name = "server"
version = "1.0.0"
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = ">= 0.56.0 and < 1.0.0"
mist = ">= 5.0.0 and < 6.0.0"
wisp = ">= 1.3.0 and < 2.0.0"
lustre = ">= 5.0.0 and < 6.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
cors_builder = ">= 2.0.2 and < 3.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
client = { path = "../client" }
shared = { path = "../shared" }
cake = ">= 2.1.0 and < 3.0.0"
sqlight = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
argv = ">= 1.0.2 and < 2.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
prng = ">= 4.0.0 and < 5.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
birl = ">= 1.7.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
